// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package mysqlserviceinstance

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstance",
		reflect.TypeOf((*MysqlServiceInstance)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "availabilityDomain", GoGetter: "AvailabilityDomain"},
			_jsii_.MemberProperty{JsiiProperty: "availabilityDomainInput", GoGetter: "AvailabilityDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupDestination", GoGetter: "BackupDestination"},
			_jsii_.MemberProperty{JsiiProperty: "backupDestinationInput", GoGetter: "BackupDestinationInput"},
			_jsii_.MemberProperty{JsiiProperty: "backups", GoGetter: "Backups"},
			_jsii_.MemberProperty{JsiiProperty: "backupsInput", GoGetter: "BackupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "baseReleaseVersion", GoGetter: "BaseReleaseVersion"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "emUrl", GoGetter: "EmUrl"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipNetwork", GoGetter: "IpNetwork"},
			_jsii_.MemberProperty{JsiiProperty: "ipNetworkInput", GoGetter: "IpNetworkInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "meteringFrequency", GoGetter: "MeteringFrequency"},
			_jsii_.MemberProperty{JsiiProperty: "meteringFrequencyInput", GoGetter: "MeteringFrequencyInput"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlConfiguration", GoGetter: "MysqlConfiguration"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlConfigurationInput", GoGetter: "MysqlConfigurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "notificationEmail", GoGetter: "NotificationEmail"},
			_jsii_.MemberProperty{JsiiProperty: "notificationEmailInput", GoGetter: "NotificationEmailInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putBackups", GoMethod: "PutBackups"},
			_jsii_.MemberMethod{JsiiMethod: "putMysqlConfiguration", GoMethod: "PutMysqlConfiguration"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "regionInput", GoGetter: "RegionInput"},
			_jsii_.MemberProperty{JsiiProperty: "releaseVersion", GoGetter: "ReleaseVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetAvailabilityDomain", GoMethod: "ResetAvailabilityDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupDestination", GoMethod: "ResetBackupDestination"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackups", GoMethod: "ResetBackups"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpNetwork", GoMethod: "ResetIpNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "resetMeteringFrequency", GoMethod: "ResetMeteringFrequency"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotificationEmail", GoMethod: "ResetNotificationEmail"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegion", GoMethod: "ResetRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetSubnet", GoMethod: "ResetSubnet"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmUser", GoMethod: "ResetVmUser"},
			_jsii_.MemberProperty{JsiiProperty: "serviceVersion", GoGetter: "ServiceVersion"},
			_jsii_.MemberProperty{JsiiProperty: "shape", GoGetter: "Shape"},
			_jsii_.MemberProperty{JsiiProperty: "shapeInput", GoGetter: "ShapeInput"},
			_jsii_.MemberProperty{JsiiProperty: "sshPublicKey", GoGetter: "SshPublicKey"},
			_jsii_.MemberProperty{JsiiProperty: "sshPublicKeyInput", GoGetter: "SshPublicKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "subnet", GoGetter: "Subnet"},
			_jsii_.MemberProperty{JsiiProperty: "subnetInput", GoGetter: "SubnetInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "vmUser", GoGetter: "VmUser"},
			_jsii_.MemberProperty{JsiiProperty: "vmUserInput", GoGetter: "VmUserInput"},
		},
		func() interface{} {
			j := jsiiProxy_MysqlServiceInstance{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceBackups",
		reflect.TypeOf((*MysqlServiceInstanceBackups)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceBackupsOutputReference",
		reflect.TypeOf((*MysqlServiceInstanceBackupsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainer", GoGetter: "CloudStorageContainer"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainerInput", GoGetter: "CloudStorageContainerInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePassword", GoGetter: "CloudStoragePassword"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePasswordInput", GoGetter: "CloudStoragePasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsername", GoGetter: "CloudStorageUsername"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsernameInput", GoGetter: "CloudStorageUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "createIfMissing", GoGetter: "CreateIfMissing"},
			_jsii_.MemberProperty{JsiiProperty: "createIfMissingInput", GoGetter: "CreateIfMissingInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStoragePassword", GoMethod: "ResetCloudStoragePassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStorageUsername", GoMethod: "ResetCloudStorageUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateIfMissing", GoMethod: "ResetCreateIfMissing"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MysqlServiceInstanceBackupsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceConfig",
		reflect.TypeOf((*MysqlServiceInstanceConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceMysqlConfiguration",
		reflect.TypeOf((*MysqlServiceInstanceMysqlConfiguration)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceMysqlConfigurationEnterpriseMonitorConfiguration",
		reflect.TypeOf((*MysqlServiceInstanceMysqlConfigurationEnterpriseMonitorConfiguration)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceMysqlConfigurationEnterpriseMonitorConfigurationOutputReference",
		reflect.TypeOf((*MysqlServiceInstanceMysqlConfigurationEnterpriseMonitorConfigurationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "emAgentPassword", GoGetter: "EmAgentPassword"},
			_jsii_.MemberProperty{JsiiProperty: "emAgentPasswordInput", GoGetter: "EmAgentPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "emAgentUsername", GoGetter: "EmAgentUsername"},
			_jsii_.MemberProperty{JsiiProperty: "emAgentUsernameInput", GoGetter: "EmAgentUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "emPassword", GoGetter: "EmPassword"},
			_jsii_.MemberProperty{JsiiProperty: "emPasswordInput", GoGetter: "EmPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "emPort", GoGetter: "EmPort"},
			_jsii_.MemberProperty{JsiiProperty: "emPortInput", GoGetter: "EmPortInput"},
			_jsii_.MemberProperty{JsiiProperty: "emUsername", GoGetter: "EmUsername"},
			_jsii_.MemberProperty{JsiiProperty: "emUsernameInput", GoGetter: "EmUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmAgentPassword", GoMethod: "ResetEmAgentPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmAgentUsername", GoMethod: "ResetEmAgentUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmPassword", GoMethod: "ResetEmPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmPort", GoMethod: "ResetEmPort"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmUsername", GoMethod: "ResetEmUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MysqlServiceInstanceMysqlConfigurationEnterpriseMonitorConfigurationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceMysqlConfigurationOutputReference",
		reflect.TypeOf((*MysqlServiceInstanceMysqlConfigurationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "connectString", GoGetter: "ConnectString"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dbName", GoGetter: "DbName"},
			_jsii_.MemberProperty{JsiiProperty: "dbNameInput", GoGetter: "DbNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "dbStorage", GoGetter: "DbStorage"},
			_jsii_.MemberProperty{JsiiProperty: "dbStorageInput", GoGetter: "DbStorageInput"},
			_jsii_.MemberProperty{JsiiProperty: "enterpriseMonitorConfiguration", GoGetter: "EnterpriseMonitorConfiguration"},
			_jsii_.MemberProperty{JsiiProperty: "enterpriseMonitorConfigurationInput", GoGetter: "EnterpriseMonitorConfigurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipAddress", GoGetter: "IpAddress"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlCharset", GoGetter: "MysqlCharset"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlCharsetInput", GoGetter: "MysqlCharsetInput"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlCollation", GoGetter: "MysqlCollation"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlCollationInput", GoGetter: "MysqlCollationInput"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlPassword", GoGetter: "MysqlPassword"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlPasswordInput", GoGetter: "MysqlPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlPort", GoGetter: "MysqlPort"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlPortInput", GoGetter: "MysqlPortInput"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlUsername", GoGetter: "MysqlUsername"},
			_jsii_.MemberProperty{JsiiProperty: "mysqlUsernameInput", GoGetter: "MysqlUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "publicIpAddress", GoGetter: "PublicIpAddress"},
			_jsii_.MemberMethod{JsiiMethod: "putEnterpriseMonitorConfiguration", GoMethod: "PutEnterpriseMonitorConfiguration"},
			_jsii_.MemberMethod{JsiiMethod: "resetDbName", GoMethod: "ResetDbName"},
			_jsii_.MemberMethod{JsiiMethod: "resetDbStorage", GoMethod: "ResetDbStorage"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnterpriseMonitorConfiguration", GoMethod: "ResetEnterpriseMonitorConfiguration"},
			_jsii_.MemberMethod{JsiiMethod: "resetMysqlCharset", GoMethod: "ResetMysqlCharset"},
			_jsii_.MemberMethod{JsiiMethod: "resetMysqlCollation", GoMethod: "ResetMysqlCollation"},
			_jsii_.MemberMethod{JsiiMethod: "resetMysqlPassword", GoMethod: "ResetMysqlPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetMysqlPort", GoMethod: "ResetMysqlPort"},
			_jsii_.MemberMethod{JsiiMethod: "resetMysqlUsername", GoMethod: "ResetMysqlUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnapshotName", GoMethod: "ResetSnapshotName"},
			_jsii_.MemberMethod{JsiiMethod: "resetSourceServiceName", GoMethod: "ResetSourceServiceName"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotName", GoGetter: "SnapshotName"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotNameInput", GoGetter: "SnapshotNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "sourceServiceName", GoGetter: "SourceServiceName"},
			_jsii_.MemberProperty{JsiiProperty: "sourceServiceNameInput", GoGetter: "SourceServiceNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MysqlServiceInstanceMysqlConfigurationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceTimeouts",
		reflect.TypeOf((*MysqlServiceInstanceTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.mysqlServiceInstance.MysqlServiceInstanceTimeoutsOutputReference",
		reflect.TypeOf((*MysqlServiceInstanceTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MysqlServiceInstanceTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
