// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package databaseserviceinstance

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstance",
		reflect.TypeOf((*DatabaseServiceInstance)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "availabilityDomain", GoGetter: "AvailabilityDomain"},
			_jsii_.MemberProperty{JsiiProperty: "availabilityDomainInput", GoGetter: "AvailabilityDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "backups", GoGetter: "Backups"},
			_jsii_.MemberProperty{JsiiProperty: "backupsInput", GoGetter: "BackupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "bringYourOwnLicense", GoGetter: "BringYourOwnLicense"},
			_jsii_.MemberProperty{JsiiProperty: "bringYourOwnLicenseInput", GoGetter: "BringYourOwnLicenseInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainer", GoGetter: "CloudStorageContainer"},
			_jsii_.MemberProperty{JsiiProperty: "computeSiteName", GoGetter: "ComputeSiteName"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "databaseConfiguration", GoGetter: "DatabaseConfiguration"},
			_jsii_.MemberProperty{JsiiProperty: "databaseConfigurationInput", GoGetter: "DatabaseConfigurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "dbaasMonitorUrl", GoGetter: "DbaasMonitorUrl"},
			_jsii_.MemberProperty{JsiiProperty: "defaultAccessRules", GoGetter: "DefaultAccessRules"},
			_jsii_.MemberProperty{JsiiProperty: "defaultAccessRulesInput", GoGetter: "DefaultAccessRulesInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "desiredState", GoGetter: "DesiredState"},
			_jsii_.MemberProperty{JsiiProperty: "desiredStateInput", GoGetter: "DesiredStateInput"},
			_jsii_.MemberProperty{JsiiProperty: "edition", GoGetter: "Edition"},
			_jsii_.MemberProperty{JsiiProperty: "editionInput", GoGetter: "EditionInput"},
			_jsii_.MemberProperty{JsiiProperty: "emUrl", GoGetter: "EmUrl"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "glassfishUrl", GoGetter: "GlassfishUrl"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "highPerformanceStorage", GoGetter: "HighPerformanceStorage"},
			_jsii_.MemberProperty{JsiiProperty: "highPerformanceStorageInput", GoGetter: "HighPerformanceStorageInput"},
			_jsii_.MemberProperty{JsiiProperty: "hybridDisasterRecovery", GoGetter: "HybridDisasterRecovery"},
			_jsii_.MemberProperty{JsiiProperty: "hybridDisasterRecoveryInput", GoGetter: "HybridDisasterRecoveryInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "identityDomain", GoGetter: "IdentityDomain"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "instantiateFromBackup", GoGetter: "InstantiateFromBackup"},
			_jsii_.MemberProperty{JsiiProperty: "instantiateFromBackupInput", GoGetter: "InstantiateFromBackupInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipNetwork", GoGetter: "IpNetwork"},
			_jsii_.MemberProperty{JsiiProperty: "ipNetworkInput", GoGetter: "IpNetworkInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipReservations", GoGetter: "IpReservations"},
			_jsii_.MemberProperty{JsiiProperty: "ipReservationsInput", GoGetter: "IpReservationsInput"},
			_jsii_.MemberProperty{JsiiProperty: "level", GoGetter: "Level"},
			_jsii_.MemberProperty{JsiiProperty: "levelInput", GoGetter: "LevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "notificationEmail", GoGetter: "NotificationEmail"},
			_jsii_.MemberProperty{JsiiProperty: "notificationEmailInput", GoGetter: "NotificationEmailInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putBackups", GoMethod: "PutBackups"},
			_jsii_.MemberMethod{JsiiMethod: "putDatabaseConfiguration", GoMethod: "PutDatabaseConfiguration"},
			_jsii_.MemberMethod{JsiiMethod: "putDefaultAccessRules", GoMethod: "PutDefaultAccessRules"},
			_jsii_.MemberMethod{JsiiMethod: "putHybridDisasterRecovery", GoMethod: "PutHybridDisasterRecovery"},
			_jsii_.MemberMethod{JsiiMethod: "putInstantiateFromBackup", GoMethod: "PutInstantiateFromBackup"},
			_jsii_.MemberMethod{JsiiMethod: "putStandby", GoMethod: "PutStandby"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "regionInput", GoGetter: "RegionInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAvailabilityDomain", GoMethod: "ResetAvailabilityDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackups", GoMethod: "ResetBackups"},
			_jsii_.MemberMethod{JsiiMethod: "resetBringYourOwnLicense", GoMethod: "ResetBringYourOwnLicense"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultAccessRules", GoMethod: "ResetDefaultAccessRules"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetDesiredState", GoMethod: "ResetDesiredState"},
			_jsii_.MemberMethod{JsiiMethod: "resetHighPerformanceStorage", GoMethod: "ResetHighPerformanceStorage"},
			_jsii_.MemberMethod{JsiiMethod: "resetHybridDisasterRecovery", GoMethod: "ResetHybridDisasterRecovery"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetInstantiateFromBackup", GoMethod: "ResetInstantiateFromBackup"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpNetwork", GoMethod: "ResetIpNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpReservations", GoMethod: "ResetIpReservations"},
			_jsii_.MemberMethod{JsiiMethod: "resetLevel", GoMethod: "ResetLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotificationEmail", GoMethod: "ResetNotificationEmail"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegion", GoMethod: "ResetRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetStandby", GoMethod: "ResetStandby"},
			_jsii_.MemberMethod{JsiiMethod: "resetSubnet", GoMethod: "ResetSubnet"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "shape", GoGetter: "Shape"},
			_jsii_.MemberProperty{JsiiProperty: "shapeInput", GoGetter: "ShapeInput"},
			_jsii_.MemberProperty{JsiiProperty: "sshPublicKey", GoGetter: "SshPublicKey"},
			_jsii_.MemberProperty{JsiiProperty: "sshPublicKeyInput", GoGetter: "SshPublicKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "standby", GoGetter: "Standby"},
			_jsii_.MemberProperty{JsiiProperty: "standbyInput", GoGetter: "StandbyInput"},
			_jsii_.MemberProperty{JsiiProperty: "status", GoGetter: "Status"},
			_jsii_.MemberProperty{JsiiProperty: "subnet", GoGetter: "Subnet"},
			_jsii_.MemberProperty{JsiiProperty: "subnetInput", GoGetter: "SubnetInput"},
			_jsii_.MemberProperty{JsiiProperty: "subscriptionType", GoGetter: "SubscriptionType"},
			_jsii_.MemberProperty{JsiiProperty: "subscriptionTypeInput", GoGetter: "SubscriptionTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "uri", GoGetter: "Uri"},
			_jsii_.MemberProperty{JsiiProperty: "version", GoGetter: "Version"},
			_jsii_.MemberProperty{JsiiProperty: "versionInput", GoGetter: "VersionInput"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstance{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceBackups",
		reflect.TypeOf((*DatabaseServiceInstanceBackups)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceBackupsOutputReference",
		reflect.TypeOf((*DatabaseServiceInstanceBackupsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainer", GoGetter: "CloudStorageContainer"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainerInput", GoGetter: "CloudStorageContainerInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePassword", GoGetter: "CloudStoragePassword"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePasswordInput", GoGetter: "CloudStoragePasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsername", GoGetter: "CloudStorageUsername"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsernameInput", GoGetter: "CloudStorageUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "createIfMissing", GoGetter: "CreateIfMissing"},
			_jsii_.MemberProperty{JsiiProperty: "createIfMissingInput", GoGetter: "CreateIfMissingInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStoragePassword", GoMethod: "ResetCloudStoragePassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStorageUsername", GoMethod: "ResetCloudStorageUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateIfMissing", GoMethod: "ResetCreateIfMissing"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstanceBackupsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceConfig",
		reflect.TypeOf((*DatabaseServiceInstanceConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceDatabaseConfiguration",
		reflect.TypeOf((*DatabaseServiceInstanceDatabaseConfiguration)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceDatabaseConfigurationOutputReference",
		reflect.TypeOf((*DatabaseServiceInstanceDatabaseConfigurationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "adminPassword", GoGetter: "AdminPassword"},
			_jsii_.MemberProperty{JsiiProperty: "adminPasswordInput", GoGetter: "AdminPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupDestination", GoGetter: "BackupDestination"},
			_jsii_.MemberProperty{JsiiProperty: "backupDestinationInput", GoGetter: "BackupDestinationInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupStorageVolumeSize", GoGetter: "BackupStorageVolumeSize"},
			_jsii_.MemberProperty{JsiiProperty: "backupStorageVolumeSizeInput", GoGetter: "BackupStorageVolumeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "characterSet", GoGetter: "CharacterSet"},
			_jsii_.MemberProperty{JsiiProperty: "characterSetInput", GoGetter: "CharacterSetInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dataStorageVolumeSize", GoGetter: "DataStorageVolumeSize"},
			_jsii_.MemberProperty{JsiiProperty: "dataStorageVolumeSizeInput", GoGetter: "DataStorageVolumeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "dbDemo", GoGetter: "DbDemo"},
			_jsii_.MemberProperty{JsiiProperty: "dbDemoInput", GoGetter: "DbDemoInput"},
			_jsii_.MemberProperty{JsiiProperty: "disasterRecovery", GoGetter: "DisasterRecovery"},
			_jsii_.MemberProperty{JsiiProperty: "disasterRecoveryInput", GoGetter: "DisasterRecoveryInput"},
			_jsii_.MemberProperty{JsiiProperty: "failoverDatabase", GoGetter: "FailoverDatabase"},
			_jsii_.MemberProperty{JsiiProperty: "failoverDatabaseInput", GoGetter: "FailoverDatabaseInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "goldenGate", GoGetter: "GoldenGate"},
			_jsii_.MemberProperty{JsiiProperty: "goldenGateInput", GoGetter: "GoldenGateInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "isRac", GoGetter: "IsRac"},
			_jsii_.MemberProperty{JsiiProperty: "isRacInput", GoGetter: "IsRacInput"},
			_jsii_.MemberProperty{JsiiProperty: "nationalCharacterSet", GoGetter: "NationalCharacterSet"},
			_jsii_.MemberProperty{JsiiProperty: "nationalCharacterSetInput", GoGetter: "NationalCharacterSetInput"},
			_jsii_.MemberProperty{JsiiProperty: "pdbName", GoGetter: "PdbName"},
			_jsii_.MemberProperty{JsiiProperty: "pdbNameInput", GoGetter: "PdbNameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupDestination", GoMethod: "ResetBackupDestination"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupStorageVolumeSize", GoMethod: "ResetBackupStorageVolumeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetCharacterSet", GoMethod: "ResetCharacterSet"},
			_jsii_.MemberMethod{JsiiMethod: "resetDataStorageVolumeSize", GoMethod: "ResetDataStorageVolumeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetDbDemo", GoMethod: "ResetDbDemo"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisasterRecovery", GoMethod: "ResetDisasterRecovery"},
			_jsii_.MemberMethod{JsiiMethod: "resetFailoverDatabase", GoMethod: "ResetFailoverDatabase"},
			_jsii_.MemberMethod{JsiiMethod: "resetGoldenGate", GoMethod: "ResetGoldenGate"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsRac", GoMethod: "ResetIsRac"},
			_jsii_.MemberMethod{JsiiMethod: "resetNationalCharacterSet", GoMethod: "ResetNationalCharacterSet"},
			_jsii_.MemberMethod{JsiiMethod: "resetPdbName", GoMethod: "ResetPdbName"},
			_jsii_.MemberMethod{JsiiMethod: "resetSid", GoMethod: "ResetSid"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnapshotName", GoMethod: "ResetSnapshotName"},
			_jsii_.MemberMethod{JsiiMethod: "resetSourceServiceName", GoMethod: "ResetSourceServiceName"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimezone", GoMethod: "ResetTimezone"},
			_jsii_.MemberMethod{JsiiMethod: "resetType", GoMethod: "ResetType"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sid", GoGetter: "Sid"},
			_jsii_.MemberProperty{JsiiProperty: "sidInput", GoGetter: "SidInput"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotName", GoGetter: "SnapshotName"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotNameInput", GoGetter: "SnapshotNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "sourceServiceName", GoGetter: "SourceServiceName"},
			_jsii_.MemberProperty{JsiiProperty: "sourceServiceNameInput", GoGetter: "SourceServiceNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timezone", GoGetter: "Timezone"},
			_jsii_.MemberProperty{JsiiProperty: "timezoneInput", GoGetter: "TimezoneInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "usableStorage", GoGetter: "UsableStorage"},
			_jsii_.MemberProperty{JsiiProperty: "usableStorageInput", GoGetter: "UsableStorageInput"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstanceDatabaseConfigurationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceDefaultAccessRules",
		reflect.TypeOf((*DatabaseServiceInstanceDefaultAccessRules)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceDefaultAccessRulesOutputReference",
		reflect.TypeOf((*DatabaseServiceInstanceDefaultAccessRulesOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "enableDbConsole", GoGetter: "EnableDbConsole"},
			_jsii_.MemberProperty{JsiiProperty: "enableDbConsoleInput", GoGetter: "EnableDbConsoleInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableDbExpress", GoGetter: "EnableDbExpress"},
			_jsii_.MemberProperty{JsiiProperty: "enableDbExpressInput", GoGetter: "EnableDbExpressInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableDbListener", GoGetter: "EnableDbListener"},
			_jsii_.MemberProperty{JsiiProperty: "enableDbListenerInput", GoGetter: "EnableDbListenerInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableEmConsole", GoGetter: "EnableEmConsole"},
			_jsii_.MemberProperty{JsiiProperty: "enableEmConsoleInput", GoGetter: "EnableEmConsoleInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableHttp", GoGetter: "EnableHttp"},
			_jsii_.MemberProperty{JsiiProperty: "enableHttpInput", GoGetter: "EnableHttpInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableHttpSsl", GoGetter: "EnableHttpSsl"},
			_jsii_.MemberProperty{JsiiProperty: "enableHttpSslInput", GoGetter: "EnableHttpSslInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableRacDbListener", GoGetter: "EnableRacDbListener"},
			_jsii_.MemberProperty{JsiiProperty: "enableRacDbListenerInput", GoGetter: "EnableRacDbListenerInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableRacOns", GoGetter: "EnableRacOns"},
			_jsii_.MemberProperty{JsiiProperty: "enableRacOnsInput", GoGetter: "EnableRacOnsInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableScanListener", GoGetter: "EnableScanListener"},
			_jsii_.MemberProperty{JsiiProperty: "enableScanListenerInput", GoGetter: "EnableScanListenerInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableSsh", GoGetter: "EnableSsh"},
			_jsii_.MemberProperty{JsiiProperty: "enableSshInput", GoGetter: "EnableSshInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableDbConsole", GoMethod: "ResetEnableDbConsole"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableDbExpress", GoMethod: "ResetEnableDbExpress"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableDbListener", GoMethod: "ResetEnableDbListener"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableEmConsole", GoMethod: "ResetEnableEmConsole"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableHttp", GoMethod: "ResetEnableHttp"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableHttpSsl", GoMethod: "ResetEnableHttpSsl"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableRacDbListener", GoMethod: "ResetEnableRacDbListener"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableRacOns", GoMethod: "ResetEnableRacOns"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableScanListener", GoMethod: "ResetEnableScanListener"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableSsh", GoMethod: "ResetEnableSsh"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstanceDefaultAccessRulesOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceHybridDisasterRecovery",
		reflect.TypeOf((*DatabaseServiceInstanceHybridDisasterRecovery)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceHybridDisasterRecoveryOutputReference",
		reflect.TypeOf((*DatabaseServiceInstanceHybridDisasterRecoveryOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainer", GoGetter: "CloudStorageContainer"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainerInput", GoGetter: "CloudStorageContainerInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePassword", GoGetter: "CloudStoragePassword"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePasswordInput", GoGetter: "CloudStoragePasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsername", GoGetter: "CloudStorageUsername"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsernameInput", GoGetter: "CloudStorageUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStoragePassword", GoMethod: "ResetCloudStoragePassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStorageUsername", GoMethod: "ResetCloudStorageUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstanceHybridDisasterRecoveryOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceInstantiateFromBackup",
		reflect.TypeOf((*DatabaseServiceInstanceInstantiateFromBackup)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceInstantiateFromBackupOutputReference",
		reflect.TypeOf((*DatabaseServiceInstanceInstantiateFromBackupOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainer", GoGetter: "CloudStorageContainer"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageContainerInput", GoGetter: "CloudStorageContainerInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePassword", GoGetter: "CloudStoragePassword"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStoragePasswordInput", GoGetter: "CloudStoragePasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsername", GoGetter: "CloudStorageUsername"},
			_jsii_.MemberProperty{JsiiProperty: "cloudStorageUsernameInput", GoGetter: "CloudStorageUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "databaseId", GoGetter: "DatabaseId"},
			_jsii_.MemberProperty{JsiiProperty: "databaseIdInput", GoGetter: "DatabaseIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "decryptionKey", GoGetter: "DecryptionKey"},
			_jsii_.MemberProperty{JsiiProperty: "decryptionKeyInput", GoGetter: "DecryptionKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "onPremise", GoGetter: "OnPremise"},
			_jsii_.MemberProperty{JsiiProperty: "onPremiseInput", GoGetter: "OnPremiseInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStoragePassword", GoMethod: "ResetCloudStoragePassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloudStorageUsername", GoMethod: "ResetCloudStorageUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetDecryptionKey", GoMethod: "ResetDecryptionKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetOnPremise", GoMethod: "ResetOnPremise"},
			_jsii_.MemberMethod{JsiiMethod: "resetServiceId", GoMethod: "ResetServiceId"},
			_jsii_.MemberMethod{JsiiMethod: "resetWalletFileContent", GoMethod: "ResetWalletFileContent"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "serviceId", GoGetter: "ServiceId"},
			_jsii_.MemberProperty{JsiiProperty: "serviceIdInput", GoGetter: "ServiceIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "walletFileContent", GoGetter: "WalletFileContent"},
			_jsii_.MemberProperty{JsiiProperty: "walletFileContentInput", GoGetter: "WalletFileContentInput"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstanceInstantiateFromBackupOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceStandby",
		reflect.TypeOf((*DatabaseServiceInstanceStandby)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceStandbyOutputReference",
		reflect.TypeOf((*DatabaseServiceInstanceStandbyOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "availabilityDomain", GoGetter: "AvailabilityDomain"},
			_jsii_.MemberProperty{JsiiProperty: "availabilityDomainInput", GoGetter: "AvailabilityDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "subnet", GoGetter: "Subnet"},
			_jsii_.MemberProperty{JsiiProperty: "subnetInput", GoGetter: "SubnetInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstanceStandbyOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceTimeouts",
		reflect.TypeOf((*DatabaseServiceInstanceTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-oraclepaas.databaseServiceInstance.DatabaseServiceInstanceTimeoutsOutputReference",
		reflect.TypeOf((*DatabaseServiceInstanceTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdate", GoMethod: "ResetUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "update", GoGetter: "Update"},
			_jsii_.MemberProperty{JsiiProperty: "updateInput", GoGetter: "UpdateInput"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseServiceInstanceTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
